/*INSERT INTO COMPANY
VALUES (1, 'COMPANY');
INSERT INTO COMPANY
VALUES (2, 'COMPANY2');

INSERT INTO USERS
VALUES (98, 'YASSINE', 'SUPER_USER', 1);
INSERT INTO USERS
VALUES (99, 'AHMED', 'COMPANY_ADMIN', 2);


INSERT INTO TASK VALUES(1,'task1','PENDING','task1',98);
INSERT INTO TASK VALUES(5,'task3','PENDING','task5',98);
INSERT INTO TASK VALUES(3,'task3','PENDING','task3',98);

INSERT INTO TASK VALUES(2,'task2','PENDING','task2',99);
INSERT INTO TASK VALUES(4,'task2','PENDING','task4',99);


INSERT INTO USERS_TASKS VALUES (98,1);
INSERT INTO USERS_TASKS VALUES (98,2);
INSERT INTO USERS_TASKS VALUES (99,3);
INSERT INTO USERS_TASKS VALUES (99,4);
INSERT INTO USERS_TASKS VALUES (99,5);

 */